/**
 * Backend for the post-operative shoulder care app.
 *
 * SECURITY MODEL
 * ---------------
 * `SHARED_TOKEN` below identifies requests as coming from this app's own
 * server-side proxy (api/checkin.js on Vercel) — it is set as an environment
 * variable there and is NEVER shipped to any browser. That alone is not
 * patient authorization, though: it just proves "this came from our proxy,"
 * not "this came from patient X."
 *
 * Patient-scoped authorization has two parts:
 *   1. A clinic staff member pre-enrolls a patient's HN (run preRegisterPatient
 *      below) BEFORE the patient ever opens the app. That creates an
 *      "unclaimed" row with a random enrollment code, which staff give the
 *      patient in person, by phone, or on discharge paperwork.
 *   2. The patient's device claims that row once, by presenting the HN and
 *      the correct enrollment code — at which point a random per-device
 *      token generated by the app gets bound to that HN, and every future
 *      request for that HN must present the same token.
 *
 * An HN with no pre-enrolled row can't be claimed by anyone, so simply
 * knowing or guessing a real HN is never enough on its own to register or
 * write data for it — the enrollment code is the proof that a request
 * really is the patient it claims to be, not just whoever asked first.
 * (An earlier version of this file bound whichever device registered
 * first, with no such code — that let anyone who knew/guessed an
 * unclaimed HN register it before the real patient did. Don't remove the
 * enrollment-code check without something equivalent replacing it.)
 *
 * If a patient gets a new phone or reinstalls the app, call
 * resetDeviceToken(hn) below (Apps Script editor: Run > select the
 * function > enter the HN when prompted) — this clears the bound device
 * token AND issues a fresh enrollment code, which you'll need to give the
 * patient again before their new device can re-claim the HN.
 *
 * SETUP — do all four steps, the last one matters most:
 *   1. Open your Google Sheet > Extensions > Apps Script.
 *   2. Delete everything in the editor and paste this whole file in. Save.
 *   3. Deploy > Manage deployments > (pencil icon) > Version: New version
 *      > Deploy. Saving alone does NOT update the live /exec URL, which is
 *      why an older copy of this script can keep answering requests.
 *   4. Check it worked: open the /exec URL in a browser. You should see
 *      {"ok":true,"service":"postoperative-care-rc","version":"...", ...}
 *      If the version does not match the one below, step 3 did not take.
 *
 * Access must be "Anyone" (not "Anyone with a Google account"), otherwise
 * Google answers with a login page the app cannot follow.
 *
 * Then set this script's URL and token in Vercel (Project Settings >
 * Environment Variables) as APPS_SCRIPT_URL and APPS_SCRIPT_TOKEN — see
 * apps-script/README.md.
 *
 * Before a new patient's first use, run preRegisterPatient(hn) from this
 * editor and give them the code it prints — see apps-script/README.md.
 */

var SCRIPT_VERSION = '2026-09-24b';
var SHARED_TOKEN = 'REPLACE_WITH_A_LONG_RANDOM_VALUE_THEN_SET_THE_SAME_VALUE_AS_APPS_SCRIPT_TOKEN_IN_VERCEL';

var MAX_CHECKINS_PER_HN_PER_HOUR = 30; // generous for real use, low enough to blunt a scripted flood

var REGISTRATION_COLUMNS = ['hn', 'enrollmentCode', 'deviceToken', 'surgeryDate', 'consent', 'registeredAt'];
var CHECKIN_COLUMNS = ['hn', 'date', 'submittedAt', 'surgeryDate', 'phase', 'painScore',
  'exercisesDoneCount', 'exercisesTotalCount', 'exercisesDoneNames', 'receivedAt'];

function jsonReply(payload) {
  payload.version = SCRIPT_VERSION;
  return ContentService.createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}

/** Health check: open the /exec URL in a browser to confirm what is deployed. */
function doGet() {
  var sheetNames = [];
  try {
    sheetNames = SpreadsheetApp.getActiveSpreadsheet().getSheets().map(function (s) { return s.getName(); });
  } catch (err) {
    return jsonReply({ ok: false, error: 'This script is not bound to a spreadsheet: ' + err });
  }
  return jsonReply({
    ok: true,
    service: 'postoperative-care-rc',
    tokenConfigured: SHARED_TOKEN.indexOf('REPLACE') === -1,
    sheets: sheetNames
  });
}

function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      return jsonReply({ ok: false, error: 'no request body' });
    }
    var payload = JSON.parse(e.postData.contents);

    if (payload.token !== SHARED_TOKEN) {
      return jsonReply({ ok: false, error: 'invalid token — the proxy and this script are using different APPS_SCRIPT_TOKEN values' });
    }
    if (!validHn(payload.hn)) {
      return jsonReply({ ok: false, error: 'invalid or missing hn' });
    }
    if (!validDeviceToken(payload.deviceToken)) {
      return jsonReply({ ok: false, error: 'invalid or missing deviceToken' });
    }

    if (payload.type === 'checkin') {
      return jsonReply(handleCheckin(payload));
    }
    return jsonReply(handleRegistration(payload));
  } catch (err) {
    return jsonReply({ ok: false, error: String(err) });
  }
}

function validHn(hn) {
  return typeof hn === 'string' && hn.length > 0 && hn.length <= 32 && /^[A-Za-z0-9\-\/ ]+$/.test(hn);
}

function validDeviceToken(token) {
  return typeof token === 'string' && /^[0-9a-f]{16,128}$/.test(token);
}

/** Rejects a request over MAX_CHECKINS_PER_HN_PER_HOUR for the same HN — a scripted-flood guard, not a clinical limit. */
function rateLimited(hn) {
  var cache = CacheService.getScriptCache();
  var key = 'rl_' + hn;
  var count = Number(cache.get(key) || '0') + 1;
  cache.put(key, String(count), 3600); // 1 hour window
  return count > MAX_CHECKINS_PER_HN_PER_HOUR;
}

function ensureSheet(name, columns) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(name);
  if (!sheet) {
    sheet = ss.insertSheet(name);
    sheet.appendRow(columns);
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function cellToString(value) {
  if (value instanceof Date) return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  return String(value === undefined || value === null ? '' : value);
}

// Google Sheets treats a cell starting with = + - @ as a formula. Every
// string value here can originate from patient input, so nothing is written
// to a cell without this guard.
function sanitizeForSheet(value) {
  if (typeof value !== 'string') return value;
  return /^[=+\-@]/.test(value) ? "'" + value : value;
}

function rowFor(columns, payload) {
  return columns.map(function (col) {
    if (col === 'receivedAt' || col === 'registeredAt') return new Date();
    return sanitizeForSheet(payload[col] === undefined ? '' : payload[col]);
  });
}

/**
 * A registration row's enrollmentCode column is set once, by staff, via
 * preRegisterPatient — it is never overwritten from a client request (the
 * client's submitted code is a claim credential to check against it, not a
 * new value to store), so this always preserves whatever staff provisioned.
 */
function registrationRow(payload, existingCode) {
  return REGISTRATION_COLUMNS.map(function (col) {
    if (col === 'registeredAt') return new Date();
    if (col === 'enrollmentCode') return existingCode;
    return sanitizeForSheet(payload[col] === undefined ? '' : payload[col]);
  });
}

function handleRegistration(payload) {
  var sheet = ensureSheet('Registrations', REGISTRATION_COLUMNS);
  var columns = REGISTRATION_COLUMNS;
  var data = sheet.getDataRange().getValues();
  var hnCol = columns.indexOf('hn');
  var codeCol = columns.indexOf('enrollmentCode');
  var tokenCol = columns.indexOf('deviceToken');

  for (var r = 1; r < data.length; r++) {
    if (cellToString(data[r][hnCol]) !== cellToString(payload.hn)) continue;
    var boundToken = cellToString(data[r][tokenCol]);
    var storedCode = cellToString(data[r][codeCol]);

    if (boundToken !== '') {
      if (boundToken !== payload.deviceToken) {
        return { ok: false, error: 'hn already registered to a different device — contact the clinic to reset it' };
      }
      // Same already-verified device re-registering (e.g. edited surgery
      // date) — no need to re-check the enrollment code.
      sheet.getRange(r + 1, 1, 1, columns.length).setValues([registrationRow(payload, storedCode)]);
      return { ok: true, action: 'updated', row: r + 1 };
    }

    // Unclaimed row: the enrollment code is the only thing standing between
    // "I know this HN" and "I can write this patient's clinical data."
    if (storedCode === '' || cellToString(payload.enrollmentCode) !== storedCode) {
      return { ok: false, error: 'invalid enrollment code' };
    }
    sheet.getRange(r + 1, 1, 1, columns.length).setValues([registrationRow(payload, storedCode)]);
    return { ok: true, action: 'registered', row: r + 1 };
  }

  // No pre-enrolled row for this hn — nothing exists to claim, by design.
  return { ok: false, error: 'hn is not recognized — ask the clinic to enroll you first' };
}

function handleCheckin(payload) {
  var regSheet = ensureSheet('Registrations', REGISTRATION_COLUMNS);
  var regData = regSheet.getDataRange().getValues();
  var regHnCol = REGISTRATION_COLUMNS.indexOf('hn');
  var regTokenCol = REGISTRATION_COLUMNS.indexOf('deviceToken');

  var bound = null;
  for (var r = 1; r < regData.length; r++) {
    if (cellToString(regData[r][regHnCol]) === cellToString(payload.hn)) { bound = cellToString(regData[r][regTokenCol]); break; }
  }
  if (bound === null || bound === '') {
    return { ok: false, error: 'hn is not registered — the app should register before checking in' };
  }
  if (bound !== payload.deviceToken) {
    return { ok: false, error: 'device token does not match this hn\'s registration' };
  }
  if (rateLimited(payload.hn)) {
    return { ok: false, error: 'rate limited' };
  }

  var sheet = ensureSheet('CheckIns', CHECKIN_COLUMNS);
  var columns = CHECKIN_COLUMNS;
  var data = sheet.getDataRange().getValues();
  var hnCol = columns.indexOf('hn');
  var dateCol = columns.indexOf('date');

  for (var i = 1; i < data.length; i++) {
    if (cellToString(data[i][hnCol]) !== cellToString(payload.hn)) continue;
    if (cellToString(data[i][dateCol]) !== cellToString(payload.date)) continue;
    // Same patient, same day — merge/overwrite rather than append (idempotent retries).
    sheet.getRange(i + 1, 1, 1, columns.length).setValues([rowFor(columns, payload)]);
    return { ok: true, action: 'merged', row: i + 1 };
  }

  sheet.appendRow(rowFor(columns, payload));
  return { ok: true, action: 'inserted', row: sheet.getLastRow() };
}

function generateEnrollmentCode() {
  var chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no 0/O/1/I — easy to read aloud or copy
  var code = '';
  for (var i = 0; i < 8; i++) {
    if (i === 4) code += '-';
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}

/**
 * Run this from the Apps Script editor BEFORE a patient's first use (select
 * preRegisterPatient from the function dropdown, then Run — it will prompt
 * for the HN). Creates the unclaimed row the patient's device needs to be
 * able to register at all, and shows you the code to give them.
 */
function preRegisterPatient(hn) {
  var ui = SpreadsheetApp.getUi();
  if (!hn) {
    var resp = ui.prompt('Enroll which HN?');
    if (resp.getSelectedButton() !== ui.Button.OK) return;
    hn = resp.getResponseText().trim();
  }
  if (!validHn(hn)) { ui.alert('That HN doesn\'t look valid — letters, numbers, "-", "/" and spaces only, up to 32 characters.'); return; }

  var sheet = ensureSheet('Registrations', REGISTRATION_COLUMNS);
  var data = sheet.getDataRange().getValues();
  var hnCol = REGISTRATION_COLUMNS.indexOf('hn');
  for (var r = 1; r < data.length; r++) {
    if (cellToString(data[r][hnCol]) === cellToString(hn)) { ui.alert('HN ' + hn + ' is already enrolled.'); return; }
  }

  var code = generateEnrollmentCode();
  var row = REGISTRATION_COLUMNS.map(function (col) {
    if (col === 'hn') return hn;
    if (col === 'enrollmentCode') return code;
    return '';
  });
  sheet.appendRow(row);
  ui.alert('Enrollment code for ' + hn + ':\n\n' + code + '\n\nGive this to the patient — they\'ll enter it once, the first time they set up the app.');
  return code;
}

/**
 * Run this from the Apps Script editor when a patient needs to switch
 * devices (lost/replaced phone, reinstalled the app). Clears the bound
 * device token AND issues a fresh enrollment code — the old code stops
 * working, so give the patient the new one.
 */
function resetDeviceToken(hn) {
  var ui = SpreadsheetApp.getUi();
  if (!hn) {
    var resp = ui.prompt('Reset device for which HN?');
    if (resp.getSelectedButton() !== ui.Button.OK) return;
    hn = resp.getResponseText().trim();
  }
  var sheet = ensureSheet('Registrations', REGISTRATION_COLUMNS);
  var data = sheet.getDataRange().getValues();
  var hnCol = REGISTRATION_COLUMNS.indexOf('hn');
  var codeCol = REGISTRATION_COLUMNS.indexOf('enrollmentCode');
  var tokenCol = REGISTRATION_COLUMNS.indexOf('deviceToken');
  for (var r = 1; r < data.length; r++) {
    if (cellToString(data[r][hnCol]) === cellToString(hn)) {
      var newCode = generateEnrollmentCode();
      sheet.getRange(r + 1, tokenCol + 1).setValue('');
      sheet.getRange(r + 1, codeCol + 1).setValue(newCode);
      var msg = 'Cleared the device for ' + hn + '. New enrollment code: ' + newCode + ' — give this to the patient for their new device (the old code no longer works).';
      ui.alert(msg);
      return msg;
    }
  }
  var msg2 = 'No registration found for ' + hn;
  ui.alert(msg2);
  return msg2;
}

/** Run this once from the editor to create the tabs and confirm access. */
function setUpSheets() {
  ensureSheet('Registrations', REGISTRATION_COLUMNS);
  ensureSheet('CheckIns', CHECKIN_COLUMNS);
  return 'Created/verified: Registrations, CheckIns';
}
