/**
 * Backend for the post-operative shoulder care app.
 *
 * HOW PATIENTS GET IN
 * -------------------
 * Any patient with a hospital number (HN) can set the app up on their own
 * phone and start sending check-ins — nobody at the clinic has to create an
 * account or issue a code first. Each phone gets its own random device ID
 * (generated by the app, never shown to anyone), and every row written here
 * records which device sent it.
 *
 * What that does and doesn't protect:
 *   - `SHARED_TOKEN` proves a request came through this app's own server
 *     (api/checkin.js on Vercel); it is never sent to any browser, so random
 *     internet traffic can't write here.
 *   - It does NOT prove a person owns the HN they typed. Someone who knows a
 *     patient's HN could submit check-ins under it from their own phone.
 *     Because of that, nothing one device sends can overwrite another
 *     device's rows (check-ins merge per HN + date + device), and when an HN
 *     has been used from more than one device, every row for it is marked in
 *     the `multipleDevices` column so staff can check with the patient
 *     (a new phone or a family member's phone is the usual reason).
 *
 * SETUP — do all four steps, the last one matters most:
 *   1. Open your Google Sheet > Extensions > Apps Script.
 *   2. Delete everything in the editor and paste this whole file in. Save.
 *   3. Deploy > Manage deployments > (pencil icon) > Version: New version
 *      > Deploy. Saving alone does NOT update the live /exec URL, which is
 *      why an older copy of this script can keep answering requests.
 *   4. Check it worked: open the /exec URL in a browser. You should see
 *      {"ok":true,"service":"postoperative-care-rc","version":"...", ...}
 *      If the version does not match the one below, step 3 did not take.
 *
 * Access must be "Anyone" (not "Anyone with a Google account"), otherwise
 * Google answers with a login page the app cannot follow.
 *
 * The URL and token also have to be set in Vercel (Project Settings >
 * Environment Variables) as APPS_SCRIPT_URL and APPS_SCRIPT_TOKEN — see
 * apps-script/README.md.
 */

var SCRIPT_VERSION = '2026-09-26b';
var SHARED_TOKEN = 'REPLACE_WITH_A_LONG_RANDOM_VALUE_THEN_SET_THE_SAME_VALUE_AS_APPS_SCRIPT_TOKEN_IN_VERCEL';

var MAX_REQUESTS_PER_HN_PER_HOUR = 30; // generous for real use, low enough to blunt a scripted flood

var REGISTRATION_COLUMNS = ['hn', 'deviceId', 'surgeryDate', 'consent', 'firstSeenAt', 'lastSeenAt'];
var CHECKIN_COLUMNS = ['hn', 'date', 'submittedAt', 'surgeryDate', 'phase', 'painScore',
  'exercisesDoneCount', 'exercisesTotalCount', 'exercisesDoneNames', 'deviceId', 'multipleDevices', 'receivedAt'];
// UCLA shoulder rating scale, asked at 2, 6, 12 and 24 weeks after surgery.
// Items not asked at that time point (active lifting and strength while the
// repair is still protected) are left blank and count as 0 in the total.
// Each score sits next to the patient's answer in words, so the tab reads
// without a scoring key. [internal key, heading shown in the sheet]
var UCLA_FIELDS = [
  ['hn', 'HN'], ['timepointWeek', 'Week after surgery'], ['date', 'Date answered'], ['daysPostOp', 'Days after surgery'],
  ['total', 'UCLA total (/35)'], ['grade', 'Grade'],
  ['pain', 'Pain (/10)'], ['painAnswer', 'Pain — answer'],
  ['function', 'Function (/10)'], ['functionAnswer', 'Function — answer'],
  ['forwardFlexion', 'Lifting arm forward (/5)'], ['forwardFlexionAnswer', 'Lifting arm forward — answer'],
  ['strength', 'Strength (/5)'], ['strengthAnswer', 'Strength — answer'],
  ['satisfaction', 'Satisfaction (/5)'], ['satisfactionAnswer', 'Satisfaction — answer'],
  ['itemsAnswered', 'Questions asked'], ['surgeryDate', 'Surgery date'],
  ['multipleDevices', 'Used on more than one phone?'], ['deviceId', 'Phone ID'],
  ['submittedAt', 'Sent from phone at'], ['receivedAt', 'Received at']
];
var UCLA_COLUMNS = UCLA_FIELDS.map(function (f) { return f[0]; });
var UCLA_HEADINGS = UCLA_FIELDS.map(function (f) { return f[1]; });

// What each score means, in the words the patient chose from.
var UCLA_ANSWERS = {
  pain: { 1: 'Constant and unbearable; strong painkillers often', 2: 'Constant but bearable; strong painkillers sometimes',
    4: 'Little or none at rest; pain with light activity', 6: 'Only with heavy or certain activities',
    8: 'Occasional and slight', 10: 'No pain' },
  'function': { 1: 'Cannot use the arm', 2: 'Light activities only', 4: 'Light housework and most daily activities',
    6: 'Most housework, shopping, driving; dresses self', 8: 'Slightly limited; can work above shoulder height',
    10: 'Normal activities' },
  forwardFlexion: { 0: 'Hardly at all (under 30°)', 1: 'A little forward (30–45°)', 2: 'Below shoulder height (45–90°)',
    3: 'Just above shoulder height (90–120°)', 4: 'Above head, not fully up (120–150°)', 5: 'Fully or nearly fully up (over 150°)' },
  strength: { 0: 'Grade 0 — no muscle contraction', 1: 'Grade 1 — muscle tightens, arm does not move',
    2: 'Grade 2 — moves only when supported', 3: 'Grade 3 — lifts arm, cannot hold anything',
    4: 'Grade 4 — lifts and holds light things, weaker than other arm', 5: 'Grade 5 — normal strength' },
  satisfaction: { 5: 'Satisfied — better', 0: 'Not satisfied — worse' }
};

// One row per patient, rewritten whenever anything arrives for them.
var SUMMARY_FIELDS = [
  ['hn', 'HN'], ['surgeryDate', 'Surgery date'],
  ['lastCheckin', 'Last check-in'], ['latestPain', 'Latest pain (0–10)'], ['avgPain', 'Average pain, last 7 check-ins'],
  ['checkinCount', 'Check-ins sent'],
  ['ucla2', 'UCLA week 2 (/35)'], ['ucla6', 'UCLA week 6 (/35)'], ['ucla12', 'UCLA week 12 (/35)'], ['ucla24', 'UCLA week 24 (/35)'],
  ['latestGrade', 'Latest UCLA grade'], ['multipleDevices', 'Used on more than one phone?'], ['updatedAt', 'Last updated']
];
var SUMMARY_COLUMNS = SUMMARY_FIELDS.map(function (f) { return f[0]; });
var SUMMARY_HEADINGS = SUMMARY_FIELDS.map(function (f) { return f[1]; });
var UCLA_TIMEPOINTS = [2, 6, 12, 24];
var MULTI_DEVICE_FLAG = 'YES — check with patient';

function jsonReply(payload) {
  payload.version = SCRIPT_VERSION;
  return ContentService.createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}

/** Health check: open the /exec URL in a browser to confirm what is deployed. */
function doGet() {
  var sheetNames = [];
  try {
    sheetNames = SpreadsheetApp.getActiveSpreadsheet().getSheets().map(function (s) { return s.getName(); });
  } catch (err) {
    return jsonReply({ ok: false, error: 'This script is not bound to a spreadsheet: ' + err });
  }
  return jsonReply({
    ok: true,
    service: 'postoperative-care-rc',
    tokenConfigured: SHARED_TOKEN.indexOf('REPLACE') === -1,
    sheets: sheetNames
  });
}

function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      return jsonReply({ ok: false, error: 'no request body' });
    }
    var payload = JSON.parse(e.postData.contents);
    // Canonicalize here too, not just in the app: older app versions send the
    // HN as typed, and one patient must never split into two identities.
    payload.hn = normalizeHn(payload.hn);

    if (payload.token !== SHARED_TOKEN) {
      return jsonReply({ ok: false, error: 'invalid token — the proxy and this script are using different APPS_SCRIPT_TOKEN values' });
    }
    if (!validHn(payload.hn)) {
      return jsonReply({ ok: false, error: 'invalid or missing hn' });
    }
    if (!validDeviceToken(payload.deviceToken)) {
      return jsonReply({ ok: false, error: 'invalid or missing deviceToken' });
    }
    if (rateLimited(payload.hn)) {
      return jsonReply({ ok: false, error: 'rate limited' });
    }

    var lock = LockService.getScriptLock(); // two phones writing at once must not interleave rows
    lock.waitLock(10000);
    try {
      if (payload.type === 'checkin') return jsonReply(handleCheckin(payload));
      if (payload.type === 'ucla') return jsonReply(handleUcla(payload));
      return jsonReply(handleRegistration(payload));
    } finally {
      lock.releaseLock();
    }
  } catch (err) {
    return jsonReply({ ok: false, error: String(err) });
  }
}

// Same rules as normalizeHn() in index.html: "HN 1234567", "hn:1234567" and
// Thai digits all become "1234567".
function normalizeHn(raw) {
  return String(raw === undefined || raw === null ? '' : raw)
    .replace(/[๐-๙]/g, function (d) { return String('๐๑๒๓๔๕๖๗๘๙'.indexOf(d)); })
    .trim()
    .replace(/^HN\s*[:.\-#]?\s*/i, '')
    .replace(/\s+/g, ' ')
    .toUpperCase();
}

function validHn(hn) {
  return typeof hn === 'string' && hn.length > 0 && hn.length <= 32 && /^[A-Za-z0-9\-\/ ]+$/.test(hn);
}

function validDeviceToken(token) {
  return typeof token === 'string' && /^[0-9a-f]{16,128}$/.test(token);
}

// The full device token never goes in the Sheet (anyone who can read the
// Sheet could otherwise replay it); a short one-way fingerprint is enough to
// tell phones apart.
function deviceIdFor(token) {
  var digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, token);
  return digest.slice(0, 6).map(function (b) { return ((b + 256) % 256).toString(16).padStart(2, '0'); }).join('');
}

/** Rejects a request over MAX_REQUESTS_PER_HN_PER_HOUR for the same HN — a scripted-flood guard, not a clinical limit. */
function rateLimited(hn) {
  var cache = CacheService.getScriptCache();
  var key = 'rl_' + hn;
  var count = Number(cache.get(key) || '0') + 1;
  cache.put(key, String(count), 3600); // 1 hour window
  return count > MAX_REQUESTS_PER_HN_PER_HOUR;
}

/**
 * Creates the tab if missing. A tab left over from an earlier version of this
 * script is handled without anyone having to touch the Sheet: if it only has
 * its header row it gets the current header; if it holds data under a
 * different header, it is renamed "<name> (old)" with its data untouched and a
 * fresh tab takes its place — never written into with columns in the wrong
 * places, and never an upload outage while waiting for someone to notice.
 */
function ensureSheet(name, columns) {
  var headings = HEADINGS_FOR[name] || columns;
  return ensureSheetWithHeadings(name, headings);
}

var HEADINGS_FOR = { 'UCLA': UCLA_HEADINGS, 'Patient Summary': SUMMARY_HEADINGS };

function ensureSheetWithHeadings(name, columns) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(name);
  if (sheet) {
    var data = sheet.getDataRange().getValues();
    var header = (data[0] || []).map(cellToString);
    if (header.join('|') === columns.join('|')) return sheet;
    if (data.length <= 1) {
      sheet.clear();
      writeHeader(sheet, columns);
      return sheet;
    }
    sheet.setName(unusedSheetName(ss, name + ' (old)'));
  }
  sheet = ss.insertSheet(name);
  writeHeader(sheet, columns);
  return sheet;
}

function writeHeader(sheet, columns) {
  sheet.appendRow(columns);
  sheet.setFrozenRows(1);
  try { // looks only — never let formatting stop a row being saved
    sheet.getRange(1, 1, 1, columns.length).setFontWeight('bold').setBackground('#E8EEF7').setWrap(true);
  } catch (err) { /* ignore */ }
}

function unusedSheetName(ss, base) {
  var candidate = base;
  for (var i = 2; ss.getSheetByName(candidate); i++) candidate = base + ' ' + i;
  return candidate;
}

function cellToString(value) {
  if (value instanceof Date) return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  return String(value === undefined || value === null ? '' : value);
}

// Google Sheets treats a cell starting with = + - @ as a formula. Every
// string value here can originate from patient input, so nothing is written
// to a cell without this guard.
function sanitizeForSheet(value) {
  if (typeof value !== 'string') return value;
  return /^[=+\-@]/.test(value) ? "'" + value : value;
}

function rowFor(columns, values) {
  return columns.map(function (col) {
    return sanitizeForSheet(values[col] === undefined || values[col] === null ? '' : values[col]);
  });
}

/** Records this device for the HN (idempotent) and returns how many devices the HN has been used from. */
function recordDevice(payload, deviceId) {
  var sheet = ensureSheet('Registrations', REGISTRATION_COLUMNS);
  var data = sheet.getDataRange().getValues();
  var hnCol = REGISTRATION_COLUMNS.indexOf('hn');
  var devCol = REGISTRATION_COLUMNS.indexOf('deviceId');
  var hn = cellToString(payload.hn);
  var devices = 0, existingRow = -1, firstSeen = null;
  for (var r = 1; r < data.length; r++) {
    if (cellToString(data[r][hnCol]) !== hn) continue;
    devices++;
    if (cellToString(data[r][devCol]) === deviceId) {
      existingRow = r;
      firstSeen = data[r][REGISTRATION_COLUMNS.indexOf('firstSeenAt')];
    }
  }
  var now = new Date();
  var values = {
    hn: payload.hn, deviceId: deviceId, surgeryDate: payload.surgeryDate,
    consent: payload.consent === false ? false : true, firstSeenAt: firstSeen || now, lastSeenAt: now
  };
  if (existingRow >= 0) {
    // Keep the consent/surgery date from registration if a check-in doesn't carry them.
    if (payload.type) values.consent = data[existingRow][REGISTRATION_COLUMNS.indexOf('consent')];
    sheet.getRange(existingRow + 1, 1, 1, REGISTRATION_COLUMNS.length).setValues([rowFor(REGISTRATION_COLUMNS, values)]);
    return { devices: devices, isNew: false };
  }
  sheet.appendRow(rowFor(REGISTRATION_COLUMNS, values));
  return { devices: devices + 1, isNew: true };
}

function handleRegistration(payload) {
  var deviceId = deviceIdFor(payload.deviceToken);
  var result = recordDevice(payload, deviceId);
  // Whenever the HN has more than one phone, not only on the request that added
  // the second one: if flagging failed partway before, a retry must finish it.
  if (result.devices > 1) markMultipleDevices(payload.hn);
  updatePatientSummary(payload.hn);
  return { ok: true, action: result.isNew ? 'registered' : 'updated', devices: result.devices };
}

function handleCheckin(payload) {
  var deviceId = deviceIdFor(payload.deviceToken);
  // A check-in also counts as registration, so a phone whose registration
  // request never arrived is still recorded.
  var reg = recordDevice(payload, deviceId);
  if (reg.devices > 1) markMultipleDevices(payload.hn); // idempotent — see handleRegistration

  var sheet = ensureSheet('CheckIns', CHECKIN_COLUMNS);
  var columns = CHECKIN_COLUMNS;
  var data = sheet.getDataRange().getValues();
  var hnCol = columns.indexOf('hn');
  var dateCol = columns.indexOf('date');
  var devCol = columns.indexOf('deviceId');

  var values = {};
  columns.forEach(function (col) { values[col] = payload[col]; });
  values.deviceId = deviceId;
  values.multipleDevices = reg.devices > 1 ? MULTI_DEVICE_FLAG : '';
  values.receivedAt = new Date();

  for (var i = 1; i < data.length; i++) {
    if (cellToString(data[i][hnCol]) !== cellToString(payload.hn)) continue;
    if (cellToString(data[i][dateCol]) !== cellToString(payload.date)) continue;
    if (cellToString(data[i][devCol]) !== deviceId) continue;
    // Same patient, same day, same phone — a retry: overwrite, don't append.
    sheet.getRange(i + 1, 1, 1, columns.length).setValues([rowFor(columns, values)]);
    updatePatientSummary(payload.hn);
    return { ok: true, action: 'merged', row: i + 1 };
  }

  sheet.appendRow(rowFor(columns, values));
  var row = sheet.getLastRow();
  updatePatientSummary(payload.hn);
  return { ok: true, action: 'inserted', row: row };
}

var UCLA_ALLOWED = {
  pain: [1, 2, 4, 6, 8, 10],
  'function': [1, 2, 4, 6, 8, 10],
  forwardFlexion: [0, 1, 2, 3, 4, 5],
  strength: [0, 1, 2, 3, 4, 5],
  satisfaction: [0, 5]
};

/** Ellman's grading of the UCLA score for rotator cuff repair. */
function uclaGrade(total) {
  if (total >= 34) return 'excellent';
  if (total >= 29) return 'good';
  if (total >= 21) return 'fair';
  return 'poor';
}

function handleUcla(payload) {
  var week = Number(payload.timepointWeek);
  if (UCLA_TIMEPOINTS.indexOf(week) === -1) return { ok: false, error: 'invalid timepointWeek' };
  if (!/^\d{4}-\d{2}-\d{2}$/.test(cellToString(payload.date))) return { ok: false, error: 'invalid date' };

  // Score here rather than trusting a total sent by the phone.
  var total = 0, answered = 0;
  var items = Object.keys(UCLA_ALLOWED);
  for (var k = 0; k < items.length; k++) {
    var v = payload[items[k]];
    if (v === null || v === undefined || v === '') continue;
    if (UCLA_ALLOWED[items[k]].indexOf(v) === -1) return { ok: false, error: 'invalid ' + items[k] };
    total += v;
    answered++;
  }
  if (payload.pain == null || payload['function'] == null || payload.satisfaction == null) {
    return { ok: false, error: 'pain, function and satisfaction are required' };
  }

  var deviceId = deviceIdFor(payload.deviceToken);
  var reg = recordDevice(payload, deviceId);
  if (reg.devices > 1) markMultipleDevices(payload.hn);

  var sheet = ensureSheet('UCLA', UCLA_COLUMNS);
  var columns = UCLA_COLUMNS;
  var values = {};
  columns.forEach(function (col) { values[col] = payload[col]; });
  values.timepointWeek = week;
  values.total = total;
  values.grade = answered === items.length ? uclaGrade(total) : ''; // a grade only means something for the full scale
  values.itemsAnswered = answered + ' of ' + items.length;
  values.deviceId = deviceId;
  values.grade = values.grade ? values.grade.charAt(0).toUpperCase() + values.grade.slice(1)
                              : 'Not graded (partial)';
  items.forEach(function (item) {
    var v = payload[item];
    values[item + 'Answer'] = (v === null || v === undefined || v === '') ? notAskedText(item, week) : UCLA_ANSWERS[item][v];
  });
  if (payload.forwardFlexion === 0 && /not yet/i.test(cellToString(payload.flexionNote))) {
    values.forwardFlexionAnswer = 'Not yet allowed to lift the arm by itself (scored 0)';
  }
  values.multipleDevices = reg.devices > 1 ? MULTI_DEVICE_FLAG : '';
  values.receivedAt = new Date();

  var data = sheet.getDataRange().getValues();
  var hnCol = columns.indexOf('hn'), weekCol = columns.indexOf('timepointWeek'), devCol = columns.indexOf('deviceId');
  for (var i = 1; i < data.length; i++) {
    if (cellToString(data[i][hnCol]) !== cellToString(payload.hn)) continue;
    if (Number(data[i][weekCol]) !== week) continue;
    if (cellToString(data[i][devCol]) !== deviceId) continue;
    // Same patient, same time point, same phone — a retry: overwrite, don't append.
    sheet.getRange(i + 1, 1, 1, columns.length).setValues([rowFor(columns, values)]);
    updatePatientSummary(payload.hn);
    return { ok: true, action: 'merged', row: i + 1, total: total };
  }
  sheet.appendRow(rowFor(columns, values));
  var row = sheet.getLastRow();
  updatePatientSummary(payload.hn);
  return { ok: true, action: 'inserted', row: row, total: total };
}

function notAskedText(item, week) {
  if (item === 'forwardFlexion') return 'Not asked — arm still protected (scored 0)';
  if (item === 'strength') return 'Not asked before week 12 (scored 0)';
  return '';
}

function numberOrBlank(v) {
  return (v === '' || v === null || v === undefined || isNaN(Number(v))) ? '' : Number(v);
}

/** Rewrites this patient's one row in "Patient Summary" from what is in the other tabs. */
function updatePatientSummary(hn) {
  hn = cellToString(hn);
  var s = { hn: hn, surgeryDate: '', lastCheckin: '', latestPain: '', avgPain: '', checkinCount: 0,
    ucla2: '', ucla6: '', ucla12: '', ucla24: '', latestGrade: '', multipleDevices: '', updatedAt: new Date() };

  var reg = ensureSheet('Registrations', REGISTRATION_COLUMNS).getDataRange().getValues();
  var devices = 0;
  for (var r = 1; r < reg.length; r++) {
    if (cellToString(reg[r][0]) !== hn) continue;
    devices++;
    var sd = cellToString(reg[r][REGISTRATION_COLUMNS.indexOf('surgeryDate')]);
    if (sd) s.surgeryDate = sd;
  }
  if (devices > 1) s.multipleDevices = MULTI_DEVICE_FLAG;

  var ci = ensureSheet('CheckIns', CHECKIN_COLUMNS).getDataRange().getValues();
  var dCol = CHECKIN_COLUMNS.indexOf('date'), pCol = CHECKIN_COLUMNS.indexOf('painScore'), sdCol = CHECKIN_COLUMNS.indexOf('surgeryDate');
  var mine = [];
  for (var c = 1; c < ci.length; c++) {
    if (cellToString(ci[c][0]) === hn) mine.push({ date: cellToString(ci[c][dCol]), pain: numberOrBlank(ci[c][pCol]), sd: cellToString(ci[c][sdCol]) });
  }
  mine.sort(function (a, b) { return a.date < b.date ? -1 : a.date > b.date ? 1 : 0; });
  s.checkinCount = mine.length;
  if (mine.length) {
    var last = mine[mine.length - 1];
    s.lastCheckin = last.date;
    s.latestPain = last.pain;
    if (last.sd) s.surgeryDate = last.sd;
    var recent = mine.slice(-7).filter(function (m) { return m.pain !== ''; });
    if (recent.length) {
      var sum = recent.reduce(function (t, m) { return t + m.pain; }, 0);
      s.avgPain = Math.round(sum / recent.length * 10) / 10;
    }
  }

  var uSheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('UCLA');
  if (uSheet) {
    var u = uSheet.getDataRange().getValues();
    var wCol = UCLA_COLUMNS.indexOf('timepointWeek'), tCol = UCLA_COLUMNS.indexOf('total'), gCol = UCLA_COLUMNS.indexOf('grade');
    var latestWeek = 0;
    for (var k = 1; k < u.length; k++) {
      if (cellToString(u[k][0]) !== hn) continue;
      var w = Number(u[k][wCol]);
      s['ucla' + w] = numberOrBlank(u[k][tCol]);
      if (w >= latestWeek) { latestWeek = w; s.latestGrade = cellToString(u[k][gCol]); }
    }
  }

  var sheet = ensureSheet('Patient Summary', SUMMARY_COLUMNS);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (cellToString(data[i][0]) === hn) {
      sheet.getRange(i + 1, 1, 1, SUMMARY_COLUMNS.length).setValues([rowFor(SUMMARY_COLUMNS, s)]);
      return;
    }
  }
  sheet.appendRow(rowFor(SUMMARY_COLUMNS, s));
}

/** Marks every existing check-in and questionnaire for this HN once a second device appears. */
function markMultipleDevices(hn) {
  [['CheckIns', CHECKIN_COLUMNS], ['UCLA', UCLA_COLUMNS]].forEach(function (tab) {
    var sheet = ensureSheet(tab[0], tab[1]);
    var data = sheet.getDataRange().getValues();
    var hnCol = tab[1].indexOf('hn');
    var flagCol = tab[1].indexOf('multipleDevices');
    for (var r = 1; r < data.length; r++) {
      if (cellToString(data[r][hnCol]) === cellToString(hn) && cellToString(data[r][flagCol]) === '') {
        sheet.getRange(r + 1, flagCol + 1).setValue(MULTI_DEVICE_FLAG);
      }
    }
  });
}

/** Run this once from the editor to create the tabs and confirm access. */
function setUpSheets() {
  ensureSheet('Registrations', REGISTRATION_COLUMNS);
  ensureSheet('CheckIns', CHECKIN_COLUMNS);
  ensureSheet('UCLA', UCLA_COLUMNS);
  ensureSheet('Patient Summary', SUMMARY_COLUMNS);
  return 'Created/verified: Registrations, CheckIns, UCLA, Patient Summary';
}

/**
 * Run once from the editor after pasting this version to fill "Patient
 * Summary" for patients who sent data before it existed.
 */
function rebuildPatientSummary() {
  var data = ensureSheet('Registrations', REGISTRATION_COLUMNS).getDataRange().getValues();
  var seen = {};
  for (var r = 1; r < data.length; r++) {
    var hn = cellToString(data[r][0]);
    if (hn && !seen[hn]) { seen[hn] = true; updatePatientSummary(hn); }
  }
  return 'Summary rebuilt for ' + Object.keys(seen).length + ' patient(s)';
}
