/**
 * Backend for the post-operative shoulder care app.
 *
 * HOW PATIENTS GET IN
 * -------------------
 * Any patient with a hospital number (HN) can set the app up on their own
 * phone and start sending check-ins — nobody at the clinic has to create an
 * account or issue a code first. Each phone gets its own random device ID
 * (generated by the app, never shown to anyone), and every row written here
 * records which device sent it.
 *
 * What that does and doesn't protect:
 *   - `SHARED_TOKEN` proves a request came through this app's own server
 *     (api/checkin.js on Vercel); it is never sent to any browser, so random
 *     internet traffic can't write here.
 *   - It does NOT prove a person owns the HN they typed. Someone who knows a
 *     patient's HN could submit check-ins under it from their own phone.
 *     Because of that, nothing one device sends can overwrite another
 *     device's rows (check-ins merge per HN + date + device), and when an HN
 *     has been used from more than one device, every row for it is marked in
 *     the `multipleDevices` column so staff can check with the patient
 *     (a new phone or a family member's phone is the usual reason).
 *
 * SETUP — do all four steps, the last one matters most:
 *   1. Open your Google Sheet > Extensions > Apps Script.
 *   2. Delete everything in the editor and paste this whole file in. Save.
 *   3. Deploy > Manage deployments > (pencil icon) > Version: New version
 *      > Deploy. Saving alone does NOT update the live /exec URL, which is
 *      why an older copy of this script can keep answering requests.
 *   4. Check it worked: open the /exec URL in a browser. You should see
 *      {"ok":true,"service":"postoperative-care-rc","version":"...", ...}
 *      If the version does not match the one below, step 3 did not take.
 *
 * Access must be "Anyone" (not "Anyone with a Google account"), otherwise
 * Google answers with a login page the app cannot follow.
 *
 * The URL and token also have to be set in Vercel (Project Settings >
 * Environment Variables) as APPS_SCRIPT_URL and APPS_SCRIPT_TOKEN — see
 * apps-script/README.md.
 */

var SCRIPT_VERSION = '2026-09-25';
var SHARED_TOKEN = 'REPLACE_WITH_A_LONG_RANDOM_VALUE_THEN_SET_THE_SAME_VALUE_AS_APPS_SCRIPT_TOKEN_IN_VERCEL';

var MAX_REQUESTS_PER_HN_PER_HOUR = 30; // generous for real use, low enough to blunt a scripted flood

var REGISTRATION_COLUMNS = ['hn', 'deviceId', 'surgeryDate', 'consent', 'firstSeenAt', 'lastSeenAt'];
var CHECKIN_COLUMNS = ['hn', 'date', 'submittedAt', 'surgeryDate', 'phase', 'painScore',
  'exercisesDoneCount', 'exercisesTotalCount', 'exercisesDoneNames', 'deviceId', 'multipleDevices', 'receivedAt'];

function jsonReply(payload) {
  payload.version = SCRIPT_VERSION;
  return ContentService.createTextOutput(JSON.stringify(payload))
    .setMimeType(ContentService.MimeType.JSON);
}

/** Health check: open the /exec URL in a browser to confirm what is deployed. */
function doGet() {
  var sheetNames = [];
  try {
    sheetNames = SpreadsheetApp.getActiveSpreadsheet().getSheets().map(function (s) { return s.getName(); });
  } catch (err) {
    return jsonReply({ ok: false, error: 'This script is not bound to a spreadsheet: ' + err });
  }
  return jsonReply({
    ok: true,
    service: 'postoperative-care-rc',
    tokenConfigured: SHARED_TOKEN.indexOf('REPLACE') === -1,
    sheets: sheetNames
  });
}

function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      return jsonReply({ ok: false, error: 'no request body' });
    }
    var payload = JSON.parse(e.postData.contents);

    if (payload.token !== SHARED_TOKEN) {
      return jsonReply({ ok: false, error: 'invalid token — the proxy and this script are using different APPS_SCRIPT_TOKEN values' });
    }
    if (!validHn(payload.hn)) {
      return jsonReply({ ok: false, error: 'invalid or missing hn' });
    }
    if (!validDeviceToken(payload.deviceToken)) {
      return jsonReply({ ok: false, error: 'invalid or missing deviceToken' });
    }
    if (rateLimited(payload.hn)) {
      return jsonReply({ ok: false, error: 'rate limited' });
    }

    var lock = LockService.getScriptLock(); // two phones writing at once must not interleave rows
    lock.waitLock(10000);
    try {
      if (payload.type === 'checkin') return jsonReply(handleCheckin(payload));
      return jsonReply(handleRegistration(payload));
    } finally {
      lock.releaseLock();
    }
  } catch (err) {
    return jsonReply({ ok: false, error: String(err) });
  }
}

function validHn(hn) {
  return typeof hn === 'string' && hn.length > 0 && hn.length <= 32 && /^[A-Za-z0-9\-\/ ]+$/.test(hn);
}

function validDeviceToken(token) {
  return typeof token === 'string' && /^[0-9a-f]{16,128}$/.test(token);
}

// The full device token never goes in the Sheet (anyone who can read the
// Sheet could otherwise replay it); a short one-way fingerprint is enough to
// tell phones apart.
function deviceIdFor(token) {
  var digest = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, token);
  return digest.slice(0, 6).map(function (b) { return ((b + 256) % 256).toString(16).padStart(2, '0'); }).join('');
}

/** Rejects a request over MAX_REQUESTS_PER_HN_PER_HOUR for the same HN — a scripted-flood guard, not a clinical limit. */
function rateLimited(hn) {
  var cache = CacheService.getScriptCache();
  var key = 'rl_' + hn;
  var count = Number(cache.get(key) || '0') + 1;
  cache.put(key, String(count), 3600); // 1 hour window
  return count > MAX_REQUESTS_PER_HN_PER_HOUR;
}

/**
 * Creates the tab if missing. A tab left over from an earlier version of this
 * script with only its header row gets the current header; one that already
 * holds data under a different header is refused rather than written into
 * with columns in the wrong places.
 */
function ensureSheet(name, columns) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(name);
  if (!sheet) {
    sheet = ss.insertSheet(name);
    sheet.appendRow(columns);
    sheet.setFrozenRows(1);
    return sheet;
  }
  var data = sheet.getDataRange().getValues();
  var header = (data[0] || []).map(cellToString);
  if (header.join('|') === columns.join('|')) return sheet;
  if (data.length <= 1) {
    sheet.clear();
    sheet.appendRow(columns);
    sheet.setFrozenRows(1);
    return sheet;
  }
  throw new Error('The "' + name + '" tab has data under different column headings. Rename it (e.g. "' + name + ' (old)") and try again.');
}

function cellToString(value) {
  if (value instanceof Date) return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  return String(value === undefined || value === null ? '' : value);
}

// Google Sheets treats a cell starting with = + - @ as a formula. Every
// string value here can originate from patient input, so nothing is written
// to a cell without this guard.
function sanitizeForSheet(value) {
  if (typeof value !== 'string') return value;
  return /^[=+\-@]/.test(value) ? "'" + value : value;
}

function rowFor(columns, values) {
  return columns.map(function (col) {
    return sanitizeForSheet(values[col] === undefined ? '' : values[col]);
  });
}

/** Records this device for the HN (idempotent) and returns how many devices the HN has been used from. */
function recordDevice(payload, deviceId) {
  var sheet = ensureSheet('Registrations', REGISTRATION_COLUMNS);
  var data = sheet.getDataRange().getValues();
  var hnCol = REGISTRATION_COLUMNS.indexOf('hn');
  var devCol = REGISTRATION_COLUMNS.indexOf('deviceId');
  var hn = cellToString(payload.hn);
  var devices = 0, existingRow = -1, firstSeen = null;
  for (var r = 1; r < data.length; r++) {
    if (cellToString(data[r][hnCol]) !== hn) continue;
    devices++;
    if (cellToString(data[r][devCol]) === deviceId) {
      existingRow = r;
      firstSeen = data[r][REGISTRATION_COLUMNS.indexOf('firstSeenAt')];
    }
  }
  var now = new Date();
  var values = {
    hn: payload.hn, deviceId: deviceId, surgeryDate: payload.surgeryDate,
    consent: payload.consent === false ? false : true, firstSeenAt: firstSeen || now, lastSeenAt: now
  };
  if (existingRow >= 0) {
    // Keep the consent/surgery date from registration if a check-in doesn't carry them.
    if (payload.type === 'checkin') values.consent = data[existingRow][REGISTRATION_COLUMNS.indexOf('consent')];
    sheet.getRange(existingRow + 1, 1, 1, REGISTRATION_COLUMNS.length).setValues([rowFor(REGISTRATION_COLUMNS, values)]);
    return { devices: devices, isNew: false };
  }
  sheet.appendRow(rowFor(REGISTRATION_COLUMNS, values));
  return { devices: devices + 1, isNew: true };
}

function handleRegistration(payload) {
  var deviceId = deviceIdFor(payload.deviceToken);
  var result = recordDevice(payload, deviceId);
  if (result.isNew && result.devices > 1) markMultipleDevices(payload.hn);
  return { ok: true, action: result.isNew ? 'registered' : 'updated', devices: result.devices };
}

function handleCheckin(payload) {
  var deviceId = deviceIdFor(payload.deviceToken);
  // A check-in also counts as registration, so a phone whose registration
  // request never arrived is still recorded.
  var reg = recordDevice(payload, deviceId);
  if (reg.isNew && reg.devices > 1) markMultipleDevices(payload.hn);

  var sheet = ensureSheet('CheckIns', CHECKIN_COLUMNS);
  var columns = CHECKIN_COLUMNS;
  var data = sheet.getDataRange().getValues();
  var hnCol = columns.indexOf('hn');
  var dateCol = columns.indexOf('date');
  var devCol = columns.indexOf('deviceId');

  var values = {};
  columns.forEach(function (col) { values[col] = payload[col]; });
  values.deviceId = deviceId;
  values.multipleDevices = reg.devices > 1 ? 'YES — check with patient' : '';
  values.receivedAt = new Date();

  for (var i = 1; i < data.length; i++) {
    if (cellToString(data[i][hnCol]) !== cellToString(payload.hn)) continue;
    if (cellToString(data[i][dateCol]) !== cellToString(payload.date)) continue;
    if (cellToString(data[i][devCol]) !== deviceId) continue;
    // Same patient, same day, same phone — a retry: overwrite, don't append.
    sheet.getRange(i + 1, 1, 1, columns.length).setValues([rowFor(columns, values)]);
    return { ok: true, action: 'merged', row: i + 1 };
  }

  sheet.appendRow(rowFor(columns, values));
  return { ok: true, action: 'inserted', row: sheet.getLastRow() };
}

/** Marks every existing check-in for this HN once a second device appears. */
function markMultipleDevices(hn) {
  var sheet = ensureSheet('CheckIns', CHECKIN_COLUMNS);
  var data = sheet.getDataRange().getValues();
  var hnCol = CHECKIN_COLUMNS.indexOf('hn');
  var flagCol = CHECKIN_COLUMNS.indexOf('multipleDevices');
  for (var r = 1; r < data.length; r++) {
    if (cellToString(data[r][hnCol]) === cellToString(hn) && cellToString(data[r][flagCol]) === '') {
      sheet.getRange(r + 1, flagCol + 1).setValue('YES — check with patient');
    }
  }
}

/** Run this once from the editor to create the tabs and confirm access. */
function setUpSheets() {
  ensureSheet('Registrations', REGISTRATION_COLUMNS);
  ensureSheet('CheckIns', CHECKIN_COLUMNS);
  return 'Created/verified: Registrations, CheckIns';
}
